// Writes every GeoShutter app icon asset from the shapes in shapes.mjs (1024 px artwork):
// artwork/app-icon.svg, the Android adaptive icon layers, the iOS AppIcon (default,
// dark and tinted), the F-Droid listing icon, the website icon and the Android status
// icons (status-icons.mjs).
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { BOTTOM, BRACKETS, CORAL, DOT, HOLE, PIN, TOP, WHITE } from './shapes.mjs';
import { writeStatusIcons } from './status-icons.mjs';

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

const glyph = (color = true) =>
  `<path d="${BRACKETS}" fill="none" stroke="${WHITE}" stroke-width="58" stroke-linecap="round" stroke-linejoin="round"/>` +
  (color
    ? `<path d="${PIN}" fill="${CORAL}" stroke="${CORAL}" stroke-width="18" stroke-linejoin="round"/><path d="${DOT}" fill="${WHITE}"/>`
    : `<path d="${PIN} ${HOLE}" fill-rule="evenodd" fill="${WHITE}" stroke="${WHITE}" stroke-width="18" stroke-linejoin="round"/>`);
const background =
  `<defs><linearGradient id="bg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${TOP}"/>` +
  `<stop offset="1" stop-color="${BOTTOM}"/></linearGradient></defs><rect width="1024" height="1024" fill="url(#bg)"/>`;
const svg = (body, rx) =>
  '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">' +
  (rx ? `<clipPath id="r"><rect width="1024" height="1024" rx="${rx}"/></clipPath><g clip-path="url(#r)">${body}</g>` : body) +
  '</svg>\n';

async function png(svgText, file, size, opaque) {
  let image = sharp(Buffer.from(svgText), { density: 72 * size / 1024 }).resize(size, size);
  if (opaque) image = image.removeAlpha();
  await image.png().toFile(resolve(repo, file));
  console.log(`${file} (${size} px${opaque ? ', no alpha' : ''})`);
}

// Master artwork, full bleed.
const master = svg('<!-- GeoShutter app icon: camera focus brackets around a location pin. ' +
  'Generated by tools/app_icon; edit the shapes there. -->' + background + glyph());
mkdirSync(resolve(repo, 'artwork'), { recursive: true });
writeFileSync(resolve(repo, 'artwork/app-icon.svg'), master);

// Android adaptive icon: the 1024 px artwork on the 72 dp visible area of the 108 dp layers.
const vector = (comment, body, extraNs = '') => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/app_icon: ${comment} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"${extraNs}
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
${body}</vector>
`;
const group = (paths) => `    <group
        android:translateX="18"
        android:translateY="18"
        android:scaleX="0.0703125"
        android:scaleY="0.0703125">
        <path
            android:pathData="${BRACKETS}"
            android:strokeColor="#FFFFFFFF"
            android:strokeWidth="58"
            android:strokeLineCap="round"
            android:strokeLineJoin="round" />
${paths}    </group>
`;
const res = 'app/src/main/res/drawable';
writeFileSync(resolve(repo, res, 'ic_launcher_foreground.xml'), vector('the artwork scaled onto the 72 dp visible area.', group(
`        <path
            android:pathData="${PIN}"
            android:fillColor="#FFFF5A4E"
            android:strokeColor="#FFFF5A4E"
            android:strokeWidth="18"
            android:strokeLineJoin="round" />
        <path
            android:pathData="${DOT}"
            android:fillColor="#FFFFFFFF" />
`)));
writeFileSync(resolve(repo, res, 'ic_launcher_monochrome.xml'), vector('one color, for themed icons.', group(
`        <path
            android:pathData="${PIN} ${HOLE}"
            android:fillColor="#FFFFFFFF"
            android:fillType="evenOdd"
            android:strokeColor="#FFFFFFFF"
            android:strokeWidth="18"
            android:strokeLineJoin="round" />
`)));
writeFileSync(resolve(repo, res, 'ic_launcher_background.xml'), vector('the gradient spans the 72 dp visible area.',
`    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="54"
                android:startY="18"
                android:endX="54"
                android:endY="90"
                android:startColor="#FF${TOP.slice(1)}"
                android:endColor="#FF${BOTTOM.slice(1)}" />
        </aapt:attr>
    </path>
`, '\n    xmlns:aapt="http://schemas.android.com/aapt"'));

// iOS: the App Store needs the default icon without alpha; dark and tinted sit on the system's background.
const appIcon = 'iosApp/alphagps/Assets.xcassets/AppIcon.appiconset';
await png(master, `${appIcon}/icon.png`, 1024, true);
await png(svg(glyph()), `${appIcon}/icon-dark.png`, 1024, false);
await png(svg(glyph(false)), `${appIcon}/icon-tinted.png`, 1024, false);
const contents = JSON.parse(readFileSync(resolve(repo, appIcon, 'Contents.json'), 'utf8'));
contents.images = contents.images.map((image) => {
  const look = image.appearances?.find((a) => a.appearance === 'luminosity')?.value;
  const { filename, ...rest } = image;
  return { filename: { dark: 'icon-dark.png', tinted: 'icon-tinted.png' }[look] ?? 'icon.png', ...rest };
});
writeFileSync(resolve(repo, appIcon, 'Contents.json'), JSON.stringify(contents, null, 2) + '\n');

// F-Droid listing icon (full bleed; stores apply their own mask) and the website icon.
await png(master, 'fastlane/metadata/android/en-US/images/icon.png', 512, false);
writeFileSync(resolve(repo, 'website/public/icon.svg'), svg(background + glyph(), 230));

// Android status icons: notification, Quick Settings tile and widget.
writeStatusIcons(repo);
