// Writes the status icons (notification, Quick Settings tile, home-screen widget) from the
// app icon's shapes: the frame with the pin while a camera receives the location, the
// frame alone while GeoShutter waits, a camera is in standby or GeoShutter is off. Android
// vector drawables (one color; Android tints them) and SVG masters in artwork/. No
// dependencies: `node status-icons.mjs`.
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { BRACKETS, HOLE, PIN } from './shapes.mjs';

// The frame's center line (212 to 812) spans 2.5 to 21.5 dp of the 24 dp icon.
const SCALE = 19 / 600;
const OFFSET = 2.5 - 212 * SCALE;
// Heavier than the app icon's 58, so the frame holds up at status-bar size.
const FRAME_STROKE = 66;

const number = (value) => Number(value.toPrecision(7)).toString();

const icon = (comment, pin) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/app_icon: ${comment} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <group
        android:translateX="${number(OFFSET)}"
        android:translateY="${number(OFFSET)}"
        android:scaleX="${number(SCALE)}"
        android:scaleY="${number(SCALE)}">
        <path
            android:pathData="${BRACKETS}"
            android:strokeColor="#FFFFFFFF"
            android:strokeWidth="${FRAME_STROKE}"
            android:strokeLineCap="round"
            android:strokeLineJoin="round" />
${pin}    </group>
</vector>
`;

const svgIcon = (comment, pin) =>
  '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">' +
  `<!-- ${comment} Generated by tools/app_icon; edit the shapes there. -->` +
  `<g transform="translate(${number(OFFSET)} ${number(OFFSET)}) scale(${number(SCALE)})" ` +
  'fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">' +
  `<path d="${BRACKETS}" stroke-width="${FRAME_STROKE}"/>${pin}</g></svg>\n`;

export function writeStatusIcons(repo) {
  const files = {
    'app/src/main/res/drawable/ic_status_sending.xml': icon(
      'status icon while a camera receives the location, the frame with the pin.',
`        <path
            android:pathData="${PIN} ${HOLE}"
            android:fillColor="#FFFFFFFF"
            android:fillType="evenOdd"
            android:strokeColor="#FFFFFFFF"
            android:strokeWidth="18"
            android:strokeLineJoin="round" />
`),
    'app/src/main/res/drawable/ic_status_waiting.xml': icon(
      'status icon while waiting, in standby or off, the frame alone.', ''),
    // The same two icons as SVG masters, in the text color (currentColor).
    'artwork/status-icon-sending.svg': svgIcon(
      'GeoShutter status icon while a camera receives the location: the frame with the pin.',
      `<path d="${PIN} ${HOLE}" fill="currentColor" fill-rule="evenodd" stroke-width="18"/>`),
    'artwork/status-icon-waiting.svg': svgIcon(
      'GeoShutter status icon while waiting, in standby or off: the frame alone.', ''),
  };
  for (const [file, text] of Object.entries(files)) {
    writeFileSync(resolve(repo, file), text);
    console.log(file);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeStatusIcons(resolve(dirname(fileURLToPath(import.meta.url)), '../..'));
}
