// Writes the status icons (notification, Quick Settings tile, home-screen widget, Control
// Center control) from the app icon's shapes: the frame with a filled pin while a camera
// receives the location, the frame with an outlined pin while GeoShutter waits, a camera
// is in standby or GeoShutter is off. Android vector drawables (one color; Android tints
// them), SVG masters in artwork/ and iOS custom symbols. No dependencies:
// `node status-icons.mjs`.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { BRACKETS, DOT, HOLE, PIN } from './shapes.mjs';

// The frame's center line (212 to 812) spans 2.5 to 21.5 dp of the 24 dp icon.
const SCALE = 19 / 600;
const OFFSET = 2.5 - 212 * SCALE;
// Heavier than the app icon's 58, so the frame holds up at status-bar size.
const FRAME_STROKE = 66;
// The outlined pin of the waiting icon.
const PIN_STROKE = 56;

const number = (value) => Number(value.toPrecision(7)).toString();

const icon = (comment, pin) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/app_icon: ${comment} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <group
        android:translateX="${number(OFFSET)}"
        android:translateY="${number(OFFSET)}"
        android:scaleX="${number(SCALE)}"
        android:scaleY="${number(SCALE)}">
        <path
            android:pathData="${BRACKETS}"
            android:strokeColor="#FFFFFFFF"
            android:strokeWidth="${FRAME_STROKE}"
            android:strokeLineCap="round"
            android:strokeLineJoin="round" />
${pin}    </group>
</vector>
`;

const svgIcon = (comment, pin) =>
  '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">' +
  `<!-- ${comment} Generated by tools/app_icon; edit the shapes there. -->` +
  `<g transform="translate(${number(OFFSET)} ${number(OFFSET)}) scale(${number(SCALE)})" ` +
  'fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">' +
  `<path d="${BRACKETS}" stroke-width="${FRAME_STROKE}"/>${pin}</g></svg>\n`;

// Symbols take filled outlines only, so the frame's strokes are outlined here: the
// top-left bracket (corner radius 56, arms to 352), mirrored for the other corners.
const HALF = FRAME_STROKE / 2;
const TOP_LEFT = [
  ['M', 212 - HALF, 352],
  ['L', 212 - HALF, 268],
  ['A', 56 + HALF, 1, 268, 212 - HALF],
  ['L', 352, 212 - HALF],
  ['A', HALF, 1, 352, 212 + HALF],
  ['L', 268, 212 + HALF],
  ['A', 56 - HALF, 0, 212 + HALF, 268],
  ['L', 212 + HALF, 352],
  ['A', HALF, 1, 212 - HALF, 352],
];
const bracket = (mirrorX, mirrorY) => TOP_LEFT.map(([command, ...args]) => {
  const x = (value) => (mirrorX ? 1024 - value : value);
  const y = (value) => (mirrorY ? 1024 - value : value);
  if (command !== 'A') return `${command}${x(args[0])} ${y(args[1])}`;
  const [radius, sweep, px, py] = args;
  // A mirror image turns the other way round.
  return `A${radius} ${radius} 0 0 ${mirrorX !== mirrorY ? 1 - sweep : sweep} ${x(px)} ${y(py)}`;
}).join('') + 'Z';
const FRAME_OUTLINE = [bracket(false, false), bracket(true, false), bracket(true, true), bracket(false, true)].join(' ');

// The outlined pin, outlined as well: PIN is a circle (center 512 470, radius 150) whose
// sides run tangentially to the tip at 512 720. Outside, the circle and sides move out by
// half the stroke and the tip gets a round cap; inside, they move in and meet in a point.
if (PIN !== 'M392 560A150 150 0 1 1 632 560L512 720Z') {
  throw new Error('PIN changed in shapes.mjs: update the outlined pin in status-icons.mjs');
}
const PIN_OUTLINE = (() => {
  const d = PIN_STROKE / 2, cx = 512, cy = 470, r = 150;
  const left = [392, 560], right = [632, 560], tip = [512, 720];
  const normal = ([x, y]) => [(x - cx) / r, (y - cy) / r];
  const shift = ([x, y], [nx, ny], k) => `${number(x + k * nx)} ${number(y + k * ny)}`;
  const nLeft = normal(left), nRight = normal(right);
  // The tip's half-angle: sin = horizontal share of a side's direction.
  const sin = Math.abs(tip[0] - right[0]) / Math.hypot(tip[0] - right[0], tip[1] - right[1]);
  const outer = `M${shift(left, nLeft, d)}A${r + d} ${r + d} 0 1 1 ${shift(right, nRight, d)}` +
    `L${shift(tip, nRight, d)}A${d} ${d} 0 0 1 ${shift(tip, nLeft, d)}Z`;
  const inner = `M${shift(left, nLeft, -d)}L${tip[0]} ${number(tip[1] - d / sin)}` +
    `L${shift(right, nRight, -d)}A${r - d} ${r - d} 0 1 0 ${shift(left, nLeft, -d)}Z`;
  return `${outer} ${inner}`;
})();

// SF Symbols template: the 24 dp icon in the Regular variants of the three scales,
// centered on the cap height like the system's symbols; iOS derives the other weights.
const SYMBOL_VARIANTS = [
  ['Regular-S', 3.915, 1402.75, 614],
  ['Regular-M', 5, 1389.82, 1030],
  ['Regular-L', 6.45, 1372.2675, 1443],
];
const guide = (id, x1, x2, y1, y2) =>
  `  <line id="${id}" style="fill:none;stroke:#27AAE1;opacity:1;stroke-width:0.5;" x1="${x1}" x2="${x2}" y1="${y1}" y2="${y2}"/>\n`;
const REFERENCE = 'M0.993654 0L3.63775 0L29.3281-67.1323L30.0303-67.1323L30.0303-70.459L28.1226-70.459Z' +
  'M11.6885-24.4799L46.9815-24.4799L46.2315-26.7285L12.4385-26.7285Z' +
  'M55.1196 0L57.7637 0L30.6382-70.459L29.4326-70.459L29.4326-67.1323Z';
const symbol = (name, description, pin) => `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3300" height="2200">
 <!-- Generated by tools/app_icon: GeoShutter status symbol, ${description}. -->
 <g id="Notes">
  <rect height="2200" id="artboard" style="fill:white;opacity:1" width="3300" x="0" y="0"/>
  <text id="template-version" style="stroke:none;fill:black;font-family:sans-serif;font-size:13;text-anchor:end;" transform="matrix(1 0 0 1 3036 1933)">Template v.4.0</text>
  <text id="descriptive-name" style="stroke:none;fill:black;font-family:sans-serif;font-size:13;text-anchor:end;" transform="matrix(1 0 0 1 3036 1969)">${name}</text>
 </g>
 <g id="Guides">
${[['S', 696, 625.541], ['M', 1126, 1055.54], ['L', 1556, 1485.54]].map(([scale, baseline, capline]) =>
  `  <g id="H-reference" style="fill:#27AAE1;stroke:none;" transform="matrix(1 0 0 1 339 ${baseline})">\n   <path d="${REFERENCE}"/>\n  </g>\n` +
  guide(`Baseline-${scale}`, 263, 3036, baseline, baseline) + guide(`Capline-${scale}`, 263, 3036, capline, capline)).join('')}${
  guide('left-margin-Regular-M', 1389.82, 1389.82, 1030.79, 1150.12)}${
  guide('right-margin-Regular-M', 1509.87, 1509.87, 1030.79, 1150.12)} </g>
 <g id="Symbols">
${SYMBOL_VARIANTS.map(([id, scale, x, y]) => {
  const k = number(scale * SCALE);
  return `  <g id="${id}" transform="matrix(${k} 0 0 ${k} ${number(x + scale * OFFSET)} ${number(y + scale * OFFSET)})">\n` +
    `   <path d="${FRAME_OUTLINE}"/>\n` +
    `   <path d="${pin}" fill-rule="evenodd"/>\n` +
    '  </g>\n';
}).join('')} </g>
</svg>
`;
const SYMBOLS = 'iosApp/WidgetShared/Assets.xcassets';
const symbolSet = (name) => JSON.stringify({
  info: { author: 'xcode', version: 1 },
  symbols: [{ filename: `${name}.svg`, idiom: 'universal' }],
}, null, 2) + '\n';

export function writeStatusIcons(repo) {
  const files = {
    'app/src/main/res/drawable/ic_status_sending.xml': icon(
      'status icon while a camera receives the location, the frame with a filled pin.',
`        <path
            android:pathData="${PIN} ${HOLE}"
            android:fillColor="#FFFFFFFF"
            android:fillType="evenOdd"
            android:strokeColor="#FFFFFFFF"
            android:strokeWidth="18"
            android:strokeLineJoin="round" />
`),
    'app/src/main/res/drawable/ic_status_waiting.xml': icon(
      'status icon while waiting, in standby or off, the frame with an outlined pin.',
`        <path
            android:pathData="${PIN}"
            android:strokeColor="#FFFFFFFF"
            android:strokeWidth="${PIN_STROKE}"
            android:strokeLineJoin="round" />
`),
    // The same two icons as SVG masters, in the text color (currentColor).
    'artwork/status-icon-sending.svg': svgIcon(
      'GeoShutter status icon while a camera receives the location: the frame with a filled pin.',
      `<path d="${PIN} ${HOLE}" fill="currentColor" fill-rule="evenodd" stroke-width="18"/>`),
    'artwork/status-icon-waiting.svg': svgIcon(
      'GeoShutter status icon while waiting, in standby or off: the frame with an outlined pin.',
      `<path d="${PIN}" stroke-width="${PIN_STROKE}"/>`),
    // iOS custom symbols for the widget and the Control Center control (shared by the app
    // and its widget extension).
    [`${SYMBOLS}/Contents.json`]: JSON.stringify({ info: { author: 'xcode', version: 1 } }, null, 2) + '\n',
    [`${SYMBOLS}/geoshutter.status.sending.symbolset/Contents.json`]: symbolSet('geoshutter.status.sending'),
    [`${SYMBOLS}/geoshutter.status.sending.symbolset/geoshutter.status.sending.svg`]:
      symbol('geoshutter.status.sending', 'the frame with a filled pin', `${PIN} ${DOT}`),
    [`${SYMBOLS}/geoshutter.status.waiting.symbolset/Contents.json`]: symbolSet('geoshutter.status.waiting'),
    [`${SYMBOLS}/geoshutter.status.waiting.symbolset/geoshutter.status.waiting.svg`]:
      symbol('geoshutter.status.waiting', 'the frame with an outlined pin', PIN_OUTLINE),
  };
  for (const [file, text] of Object.entries(files)) {
    mkdirSync(dirname(resolve(repo, file)), { recursive: true });
    writeFileSync(resolve(repo, file), text);
    console.log(file);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeStatusIcons(resolve(dirname(fileURLToPath(import.meta.url)), '../..'));
}
