import java.util.Locale

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.android.lint)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.jetbrains.compose)

    id("androidx.room")
    id("com.google.devtools.ksp")
    alias(libs.plugins.sentry.kotlin.multiplatform)

}

compose.resources {
    publicResClass = true
    generateResClass = always
}

// Generates SupportedLanguages.kt from the Weblate-managed locale folders in
// composeResources, so merging a translation PR is the only step needed to
// register a new language (picker entries, tags and native display names).
val supportedLanguagesDir = layout.buildDirectory.dir("generated/supportedLanguages/kotlin")
val generateSupportedLanguages = tasks.register("generateSupportedLanguages") {
    val resDir = layout.projectDirectory.dir("src/commonMain/composeResources").asFile
    val localeFolders = providers.provider {
        resDir.listFiles { file: File -> file.isDirectory }.orEmpty()
            .map { it.name }
            .filter { it == "values" || it.startsWith("values-") }
            .sorted()
    }
    inputs.property("localeFolders", localeFolders)
    outputs.dir(supportedLanguagesDir)
    doLast {
        // Android resource qualifier -> BCP-47 tag; the bare "values" folder is
        // the development language, English.
        fun folderToTag(folder: String): String? {
            if (folder == "values") return "en"
            val qualifier = folder.removePrefix("values-")
            if (qualifier.startsWith("b+")) return qualifier.removePrefix("b+").replace('+', '-')
            val parts = qualifier.split("-r", limit = 2)
            val language = when (val lang = parts[0]) {
                // Android resource folders use the legacy ISO codes; BCP-47 doesn't.
                "in" -> "id"
                "iw" -> "he"
                "ji" -> "yi"
                else -> lang
            }
            // Skip non-locale qualifiers (theme, density, ...)
            if (!language.matches(Regex("[a-z]{2,3}"))) return null
            return if (parts.size == 2) "$language-${parts[1]}" else language
        }

        // The language's own name for itself, from the JDK's CLDR data.
        fun displayName(tag: String): String {
            val locale = Locale.forLanguageTag(tag)
            val name = locale.getDisplayLanguage(locale).ifBlank { tag }
            return name.replaceFirstChar { if (it.isLowerCase()) it.titlecase(locale) else it.toString() }
        }

        val tags = localeFolders.get().mapNotNull(::folderToTag).distinct()
            .sortedWith(compareBy({ it != "en" }, { it }))
        val entries = tags.joinToString("\n") { tag ->
            "        AppLanguage(tag = \"$tag\", displayName = \"${displayName(tag)}\"),"
        }
        val file = supportedLanguagesDir.get()
            .file("com/sasch/cameragps/sharednew/language/SupportedLanguages.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// GENERATED by :sharednew:generateSupportedLanguages — do not edit.
            |// Derived from the src/commonMain/composeResources/values-* folders, so a
            |// merged Weblate language lands here (and in the in-app picker) automatically.
            |package com.sasch.cameragps.sharednew.language
            |
            |object SupportedLanguages {
            |    val entries: List<AppLanguage> = listOf(
            |$entries
            |    )
            |
            |    fun fromTag(tag: String): AppLanguage? {
            |        val normalized = tag.substringBefore('-').lowercase()
            |        return entries.firstOrNull { it.tag.substringBefore('-').lowercase() == normalized }
            |    }
            |}
            |""".trimMargin()
        )
    }
}


// --- Sentry Cocoa linking (Apple targets only) --------------------------------
//
// The plugin adds the `-F` search path for the Sentry Cocoa xcframework that
// Xcode's Swift Package Manager checked out for iosApp/alphagps.xcodeproj
// (product `Sentry-Dynamic`); the published cinterop klib already carries the
// matching `-framework Sentry`.
//
// **The foss guarantee lives here.** Left at its default, the plugin injects
// `api("io.sentry:sentry-kotlin-multiplatform")` into commonMain, which would
// put the Sentry Java SDK into :sharednew's Android artifact and therefore into
// the F-Droid flavor of :app. Turning auto-install off reduces the plugin to
// pure Apple-target linking; the dependency stays declared by hand in the
// iosMain source set below. Do not remove this.
//
// Beyond that the plugin is inert for Android work: it only configures Apple
// binaries, only on a Mac host, and only when an Apple compile task is actually
// in the requested task graph.
sentryKmp {
    autoInstall.enabled.set(false)

    // Without this the plugin file-walks the repo root looking for a .xcodeproj,
    // which here means walking website/node_modules (138 MB).
    linker.xcodeprojPath.set(rootProject.layout.projectDirectory.dir("iosApp/alphagps.xcodeproj").asFile.absolutePath)
    // Escape hatch for a checkout that has never been opened in Xcode:
    // -Psentry.cocoa.frameworkPath=/path/to/Sentry-Dynamic.xcframework
    linker.frameworkPath.set(providers.gradleProperty("sentry.cocoa.frameworkPath"))
}

kotlin {

    androidLibrary {
        androidResources.enable = true
    }

    // Target declarations - add or remove as needed below. These define
    // which platforms this KMP module supports.
    // See: https://kotlinlang.org/docs/multiplatform-discover-project.html#targets
    android {
        namespace = "com.sasch.cameragps.sharednew"
        compileSdk {
            version = release(37) {
                minorApiLevel = 1
            }
        }
        minSdk = 26

        withHostTestBuilder {
        }

        withDeviceTestBuilder {
            sourceSetTreeName = "test"
        }.configure {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        }
    }

    // For iOS targets, this is also where you should
    // configure native binary output. For more information, see:
    // https://kotlinlang.org/docs/multiplatform-build-native-binaries.html#build-xcframeworks

    // A step-by-step guide on how to include this library in an XCode
    // project can be found here:
    // https://developer.android.com/kotlin/multiplatform/migrate
    val xcfName = "sharedKit"

    /* iosX64 {
         binaries.framework {
             baseName = xcfName
         }
     }*/

    iosArm64 {
        binaries.framework {
            baseName = xcfName
        }
    }

    iosSimulatorArm64 {
        binaries.framework {
            baseName = xcfName
        }
    }

    // Source set declarations.
    // Declaring a target automatically creates a source set with the same name. By default, the
    // Kotlin Gradle Plugin creates additional source sets that depend on each other, since it is
    // common to share sources between related targets.
    // See: https://kotlinlang.org/docs/multiplatform-hierarchy.html
    sourceSets {
        commonMain {
            kotlin.srcDir(generateSupportedLanguages)
            dependencies {
                implementation(libs.kotlin.stdlib)
                // Add KMP dependencies here
                implementation(libs.compose.runtime.multiplatform)
                implementation(libs.compose.foundation.multiplatform)
                implementation(libs.compose.material3.multiplatform)
                //     implementation(libs.components.resources)
                implementation(libs.navigationevent)

                //implementation(libs.androidx.sqlite.bundled)
                implementation(libs.androidx.room.runtime)
                implementation(libs.components.resources)
                implementation(libs.androidx.activity.compose)
                implementation(libs.androidx.sqlite.bundled)
                implementation(libs.logging)
                implementation(libs.kotlinx.datetime)
                implementation(libs.androidx.lifecycle.viewmodel)
                implementation(libs.lifecycle.runtime.compose)


            }
        }

        commonTest {
            dependencies {
                implementation(libs.kotlin.test)
                implementation(libs.kotlinx.coroutines.test)
            }
        }

        androidMain {
            dependencies {
                // Add Android-specific dependencies here. Note that this source set depends on
                // commonMain by default and will correctly pull the Android artifacts of any KMP
                // dependencies declared in commonMain.
                // LanguagePreference.android.kt: per-app language below API 33.
                implementation(libs.androidx.appcompat)

            }
        }

        getByName("androidDeviceTest") {
            dependencies {
                implementation(libs.androidx.runner)
                implementation(libs.androidx.core)
                implementation(libs.androidx.junit)
            }
        }

        iosMain {
            dependencies {
                // Add iOS-specific dependencies here. This a source set created by Kotlin Gradle
                // Plugin (KGP) that each specific iOS target (e.g., iosX64) depends on as
                // part of KMP’s default source set hierarchy. Note that this source set depends
                // on common by default and will correctly pull the iOS artifacts of any
                // KMP dependencies declared in commonMain.

                // Sentry stays in iosMain: moving it to commonMain would drag the
                // Sentry Java SDK into :sharednew's Android artifact and therefore
                // into the foss (F-Droid) flavor of :app, which must stay free of
                // proprietary dependencies.
                implementation(libs.sentry.kotlin.multiplatform)
            }
        }
    }

}

// The Android lint model of the host tests reads KSP's generated sources without
// declaring the dependency, which fails Gradle's task validation whenever tests
// and lint run in one build (for example `./gradlew check`).
tasks.configureEach {
    if (name == "generateAndroidHostTestLintModel" || name == "lintAnalyzeAndroidHostTest") {
        dependsOn("kspAndroidHostTest")
    }
}

dependencies {
    add("kspAndroid", libs.androidx.room.compiler)
    add("kspIosSimulatorArm64", libs.androidx.room.compiler)
    add("kspIosArm64", libs.androidx.room.compiler)
}

room {
    schemaDirectory("$projectDir/schemas")
}